version: '3.7'

services:
    nginx:
        build: ./deploytools/nginx
        volumes:
            - static_volume:/home/app/web/static
        ports:
            - 1337:80
        depends_on:
            - web

    web:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static
        expose:
            - 8000
        env_file:
            - .envs/.prod/.env.prod
        depends_on:
            - db

    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .envs/.prod/.env.prod.db

    redis:
        image: redis:alpine

volumes:
    postgres_data:
    static_volume:
