version: '3.7'

services:

    web:
        build:
            context: ./
            dockerfile: Dockerfile.prod
            cache_from:
                - eu.gcr.io/victor-ciurana-com/victorciuranacom_web:latest
        image:
                  eu.gcr.io/victor-ciurana-com/victorciuranacom_web:latest
        command: gunicorn app.config.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
            - 8000
        env_file:
            - .envs/.prod/.prod.dec.env
        depends_on:
            - redis

    nginx-proxy:
        container_name: nginx-proxy
        build: ./deploytools/nginx
        # image: eu.gcr.io/victor-ciurana-com/victorciuranacom_nginx-proxy:latest
        restart: always
        ports:
            - 443:443
            - 80:80
        volumes:
            - static_volume:/home/app/web/staticfiles
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
            - web
    nginx-proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        env_file:
            - .envs/.prod/.env.prod.proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
        depends_on:
            - "nginx-proxy"

    redis:
        image: redis:alpine

volumes:
    postgres_data:
    static_volume:
    certs:
    html:
    vhost:
