version: '3.7'

services:
  web:
    container_name: victorciuranacom_web_dev
    build: ./
    cache_from:
      eu.gcr.io/victor-ciurana-com/victorciuranacom_web_dev:latest
    image:
      eu.gcr.io/victor-ciurana-com/victorciuranacom_web_dev:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .envs/.local/.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.local/.env.dev.db

  redis:
    image: redis:alpine

volumes:
  postgres_data:
