# Generated by Django 3.2 on 2021-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
