name: CI

on: [push]

jobs:

  build:

    name: Build test and push to GCP registry
    runs-on: ubuntu-latest

    steps:

      # Set up checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up SOPS
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1
        id: install

      # Set up SSH
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOSTS }} >> ~/.ssh/known_hosts

      # Set up gcloud actions and log int
      - name: Login GCP credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # Build for tests
      - name: Pull GCR dev
        run: docker pull eu.gcr.io/victor-ciurana-com/victorciuranacom_web_dev
      - name: Build GCR dev
        run: docker build . -t eu.gcr.io/victor-ciurana-com/victorciuranacom_web_dev
      - name: Build Docker image with compose
        run: docker-compose build

      # Run liters and tests
      - name: Lint checks with black and flake8
        run: docker-compose run web pytest --black app --flake8
      - name: Pytest
        run: docker-compose run web pytest

      # If tests pass push dev
      - name: Push dev image
        run: docker push eu.gcr.io/victor-ciurana-com/victorciuranacom_web_dev


      # If test pass build prod and push
      - name: Build prod Docker image
        run: |
          sops exec-env .envs/.prod/.prod.env 'docker build . -t eu.gcr.io/victor-ciurana-com/victorciuranacom_web'
          docker push eu.gcr.io/victor-ciurana-com/victorciuranacom_web
          docker -H "ssh://admin@${{ secrets.SSH_HOSTS }}" pull eu.gcr.io/victor-ciurana-com/victorciuranacom_web
          sops exec-env .envs/.prod/.prod.env 'docker-compose -H "ssh://admin@${{ secrets.SSH_HOSTS }}" -f docker-compose.prod.yml up --force-recreate --remove-orphans -d'
          docker -H "ssh://admin@${{ secrets.SSH_HOSTS }}" image prune -af
