name: CI

on: [push]

jobs:

  build:

    name: Test job
    runs-on: ubuntu-latest
    # env:
    #   IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}

    steps:

      # Check out code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Cache the builds
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1
        id: install

      - name: Login
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Pull build dev image from registry (Google required)
        run: docker pull eu.gcr.io/victor-ciurana-com/victorciuranacom_web_dev

      - name: Build (attept cache)
        run: docker build . -t eu.gcr.io/victor-ciurana-com/victorciuranacom_web_dev

      - name: Build Docker image with compose
        run: docker-compose build

      - name: Lint checks with black and flake8
        run: docker-compose run web pytest --black app --flake8

      - name: Pytest
        run: docker-compose run web pytest

      - name: Push dev image
        run: docker push eu.gcr.io/victor-ciurana-com/victorciuranacom_web_dev

      - name: Move cache (prevent 5GB GitHub cache limit)
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # If all works push te production one

      # - name: Build Docker image
      #   run: docker build . -t $IMAGE_NAME

