name: CI

on: [push]

jobs:

  build:

    name: Test job
    runs-on: ubuntu-latest
    # env:
    #   IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}

    steps:

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1
        id: install

      - name: Login
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Build Docker image
      #   run: docker build . -t $IMAGE_NAME

      - name: Do I have kms ?
        run: |
          gcloud auth application-default login
          gcloud kms keys list --location global --keyring victorciurana-keyring

      # - name: Build Docker image with compose
      #   run: docker-compose build

      # - name: Pytest (breaks)
      #   run: docker-compose exec -T web pytest

