name: CI

on: [push]

jobs:

  build:

    name: Test job
    runs-on: ubuntu-latest

    steps:
      - name: Test build part
        run: echo "Test build part runs"

      - name: Test secrets work
        run : echo "My secret ${{ secrets.NOT_SO_SECRET }}"
